site_name: top_secret_repos/top-secret-repo-two

docs_dir: ./docs

nav:
  - Home1: "index.md"
  - More Docs:
      - Page1: "page1.md"
      - Page2: "page2.md"

theme:
  name: "material"

plugins:
  - mkdocstrings
